### ISSUE TITLE
[Bug] class file version 62.0

### ISSUE THREAD

**Issue by blepblops** [voliol/universal-pokemon-randomizer#4]
**Describe the bug**
This issue is unique to this version and does not appear on the main branch of ZX.
When launching the .bat file I receive this output:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/dabomstew/pkrandom/gui/RandomizerGUI has been compiled by a more recent version of the Java Runtime (class file version 62.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
Yes, I have the most recent version of Java.

**To Reproduce**
1. Run the .bat file
2. Receive output

**Expected behavior**
I assume it's supposed to run correctly

**System (please complete the following information):**
 - Operating System: Win10
 - Java Version: 1.8.0_411
 - Randomizer Version: 0.12.0

**Comment by voliol** [comment]
Thanks for reporting! To my understanding (i.e. what this page says: https://javaalmanac.io/bytecode/versions/) class file version 52.0 is for Java 8, while 62.0 is for Java 18. This would line up with your bug report, and this branch being built with a Java 18 SDK.

For whatever reason 8 seems to be still recommended as a standard, but there should be no issues for you downloading/installing Java 18 (or newer) on Win10. I'll look into issue some more either way. The main branch of ZX is indeed on Java 8 and I haphazardly changed that thinking little of it, but it'd be worrisome if it worsened compatibility/accessibility of the program. And best case scenario it is still a communications issue which should be put in the usage instructions.

(please report the turnout of installing Java 18, whether that solved it or not, waiting to close the issue until then)

**Comment by voliol** [comment]
A person on Reddit ran into the same problem, and updating to Java 18 fixed it. Closing the issue.
